### ISSUE TITLE
N/A label for follower count

### ISSUE THREAD

**Issue by DerMolly** [dahlia/fedi-badge#2]
I just found your tool and wanted to use it for the README page of [my bot](https://github.com/DerMolly/DailyScry), but I'm only getting N/A as a follower count. Am I missing somthing?

![CleanShot 2024-03-25 at 00 17 58](https://github.com/dahlia/fedi-badge/assets/3978662/2e30cc98-7549-479f-83f6-6d384ad24e2c)

**Comment by dahlia** [comment]
Have you turned on *Preferences* → *Public profile* → *Privacy and reach* → *Show follows and followers on profile*?

![](https://github.com/dahlia/fedi-badge/assets/12431/454455b9-ae87-4daa-8aa0-db7d3a10f116)

**Comment by DerMolly** [comment]
Yes that's activated…

**Comment by dahlia** [comment]
Oh, your instance requires requests to be signed to access the user data… I have no idea why they do, but unfortunately, your account cannot use this badge generator.  😭

```console
$ curl -H"Accept: application/activity+json" https://botsin.space/users/dailyscry
{"error":"Request not signed"}
```

**Comment by DerMolly** [comment]
Too bad, thanks for your effort.
